/'******************************************************************************************
*
*   raylib [textures] example - Load textures from raw data
*
*   NOTE: Images are loaded in CPU memory (RAM) textures are loaded in GPU memory (VRAM)
*
*   Example originally created with raylib 1.3, last time updated with raylib 3.5
*
*   Example licensed under an unmodified zlib/libpng license, which is an OSI-certified,
*   BSD-like license that allows static linking with closed source software
*
*   Copyright (c) 2015-2024 Ramon Santamaria (@raysan5)
*
*******************************************************************************************'/

#include "../../raylib.bi"

'' Initialization
''--------------------------------------------------------------------------------------
const as long screenWidth = 800
const as long screenHeight = 450

InitWindow(screenWidth, screenHeight, "raylib [textures] example - texture from raw data")

'' NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)

'' Load RAW image data (512x512, 32bit RGBA, no file header)
dim as Image fudesumiRaw = LoadImageRaw("resources/fudesumi.raw", 384, 512, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, 0)
dim as Texture2D fudesumi = LoadTextureFromImage(fudesumiRaw)  '' Upload CPU (RAM) image to GPU (VRAM)
UnloadImage(fudesumiRaw)                                '' Unload CPU (RAM) image data

'' Generate a checked texture by code
dim as long widt = 960
dim as long height = 480

'' Dynamic memory allocation to store pixels data (Color type)
dim as RLColor ptr pixels = allocate((widt * height) * sizeof(RLColor))

for y as integer = 0 to height - 1
    for x as integer = 0 to widt - 1
        if ((x / 32 + y / 32) / 1) mod 2 = 0 then
            pixels[y * widt + x] = ORANGE
        else
            pixels[y * widt + x] = GOLD
        end if
    next 
next

'' Load pixels data into an image structure and create texture
dim as Image checkedIm = Image(pixels, widt, height, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, 1)

dim as Texture2D checked = LoadTextureFromImage(checkedIm)
UnloadImage(checkedIm)         '' Unload CPU (RAM) image data (pixels)

SetTargetFPS(60)               '' Set our game to run at 60 frames-per-second
''---------------------------------------------------------------------------------------

'' Main game loop
do while not WindowShouldClose()    '' Detect window close button or ESC key
    '' Draw
    ''----------------------------------------------------------------------------------
    BeginDrawing()

        ClearBackground(RAYWHITE)

        DrawTexture(checked, screenWidth/2 - checked.width/2, screenHeight/2 - checked.height/2, Fade(WHITE, 0.5f))
        DrawTexture(fudesumi, 430, -30, WHITE)

        DrawText("CHECKED TEXTURE ", 84, 85, 30, BROWN)
        DrawText("GENERATED by CODE", 72, 148, 30, BROWN)
        DrawText("and RAW IMAGE LOADING", 46, 210, 30, BROWN)

        DrawText("(c) Fudesumi sprite by Eiden Marsal", 310, screenHeight - 20, 10, BROWN)

    EndDrawing()
    ''----------------------------------------------------------------------------------
loop

'' De-Initialization
''--------------------------------------------------------------------------------------
UnloadTexture(fudesumi)    '' Texture unloading
UnloadTexture(checked)     '' Texture unloading

CloseWindow()              '' Close window and OpenGL context
''--------------------------------------------------------------------------------------